export const ENDPOINT = process.env.APRVEL_PUBLIC_APPWRITE_ENDPOINT || '';
export const PROJECT_ID = process.env.APRVEL_PUBLIC_APPWRITE_PROJECT_ID || '';
export const API_KEY = process.env.APRVEL_APPWRITE_API_KEY || '';

export const DB_ID = process.env.APRVEL_PUBLIC_APPWRITE_DATABASE_ID || '';

export const CLAIMED_QUEUE_TABLE_ID =
  process.env.APRVEL_PUBLIC_APPWRITE_CLAIMED_QUEUE_TABLE_ID || '';
export const AVAILABLE_OIDS_TABLE_ID =
  process.env.APRVEL_PUBLIC_APPWRITE_AVAILABLE_OIDS_TABLE_ID || '';
export const ORDERS_TABLE_ID =
  process.env.APRVEL_PUBLIC_APPWRITE_ORDERS_TABLE_ID || '';
export const ORDER_LINES_TABLE_ID =
  process.env.APRVEL_PUBLIC_APPWRITE_ORDER_LINES_TABLE_ID || '';

export const SEARCH_HISTORY_TABLE_ID =
  process.env.APRVEL_PUBLIC_APPWRITE_SEARCH_HISTORY_TABLE_ID ||
  '6997bf08001b7663d1ff';

export const SPENDING_TRENDS_TABLE_ID =
  process.env.APRVEL_PUBLIC_APPWRITE_SPENDING_TRENDS_TABLE_ID || '';
export const VENDOR_SPENDING_TRENDS_TABLE_ID =
  process.env.APRVEL_PUBLIC_APPWRITE_VENDOR_SPENDING_TRENDS_TABLE_ID || '';
export const NOTIFICATIONS_TABLE_ID =
  process.env.APRVEL_PUBLIC_APPWRITE_NOTIFICATIONS_TABLE_ID || '';
